name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run Lint
    runs-on: ubuntu-latest    

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: yarn install

    - name: Run lint fix
      run: yarn fix

  test:
    name: Run Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js 16.17.1
      uses: actions/setup-node@v2
      with:
        node-version: 16.17.1

    - name: Install dependencies
      run: yarn install

    - name: Run test
      run: yarn test
