name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    
    - uses: actions/cache@v3
      id: node_modules_cache_id
      env:
        cache-name: cache-node-modules
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
    
    - run: echo '${{ toJSON(steps.node_modules_cache_id.outputs) }}'
    
    - if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}
      run: yarn install
    
    - run: yarn list --depth=0
    
    - name: Run tests
      run: yarn test
